org: ${env:SLS_ORG}
app: ${env:SLS_APP}
service: ${env:SLS_SERVICE}
useDotenv: true
variablesResolutionMode: 20210326

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpack:
    keepOutputDirectory: true
    webpackConfig: webpack.config.js
    includeModules:
      forceInclude:
        - bignumber.js
        - node-fetch
        - stellar-sdk
        - lodash
      forceExclude:
        - aws-sdk
    packager: yarn
  provisionedConcurrency:
    paid: 4
    free: 0

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'testnet'}
  lambdaHashingVersion: 20201221
  environment:
    turretBaseUrl: ${env:SLS_TURRET_BASE_URL}
    turretSigner: ${env:SLS_TURRET_SIGNER_ACCOUNT}
  tracing:
    lambda: true
  httpApi:
    cors: true

functions:
  run:
    handler: src/app.default
    # If you're not on a paid plan with AWS you'll need to use 0 (i.e. 'free'), otherwise you'll get an RunLambdaEvConf error
    provisionedConcurrency: ${self:custom.provisionedConcurrency.${env:SLS_AWS_PLAN}, self:custom.provisionedConcurrency.free}
    memorySize: 256
    timeout: ${env:SLS_TURRET_SIGNER_ACCOUNT, 8}
    events:
      - httpApi:
          method: POST
          path: /{txFunctionHash}
      - httpApi:
          method: GET
          path: /